### ISSUE TITLE
Cannot multiplex requests on a single H2 connection

### ISSUE THREAD

**Issue by nicolas-grekas** [amphp/http-client#246] opened 2020-01-08 15:57 UTC
Spotted at https://github.com/symfony/symfony/pull/35115#issuecomment-572057741

The following script adapted from the examples doesn't multiplex the requests.
Note that we limit to one single connection. If we remove this limit, one connection per request is made and all works concurrently - but then this is no different than using HTTP/1.1.

```php
<?php

use Amp\Http\Client\Connection\LimitedConnectionPool;
use Amp\Http\Client\Connection\UnlimitedConnectionPool;
use Amp\Http\Client\HttpClientBuilder;
use Amp\Http\Client\HttpException;
use Amp\Http\Client\Request;
use Amp\Http\Client\Response;
use Amp\Loop;
use Amp\Sync\LocalKeyedSemaphore;

require __DIR__ . '/vendor/autoload.php';

Loop::run(static function () use ($argv) {
    $uris = [];

    for ($i = 0; $i < 379; ++$i) {
        $uris[] = "https://http2.akamai.com/demo/tile-$i.png";
    }

    // Instantiate the HTTP client
    $pool = LimitedConnectionPool::byHost(new UnlimitedConnectionPool, new LocalKeyedSemaphore(1));
    $client = (new HttpClientBuilder)
            ->usingPool($pool)
            ->build();

    $requestHandler = static function (string $uri) use ($client) {
        /** @var Response $response */
        $response = yield $client->request(new Request($uri));

        return yield $response->getBody()->buffer();
    };

    try {
        $promises = [];

        foreach ($uris as $uri) {
            $promises[$uri] = Amp\call($requestHandler, $uri);
        }

        $bodies = yield $promises;

        foreach ($bodies as $uri => $body) {
            print $uri . " - " . \strlen($body) . " bytes" . PHP_EOL;
        }
    } catch (HttpException $error) {
        // If something goes wrong Amp will throw the exception where the promise was yielded.
        // The HttpClient::request() method itself will never throw directly, but returns a promise.
        echo $error;
    }
});
```

**Comment by kelunik** [comment] 2020-01-08 16:37
Indeed, currently it limits concurrent requests instead of concurrent connections. I guess having the same connection limit for both isn't what users generally want.

**Comment by nicolas-grekas** [comment] 2020-01-08 19:39
> having the same connection limit for both isn't what users generally want.

sure! Note that this is not my issue here :) Is there a way to multiplex several requests on a single h2 connection? That's what I don't know how to do here. Is that a known limitation?

**Comment by kelunik** [comment] 2020-01-08 20:58
Sure, that will happen by default, but if you limit to a single concurrent request, it will obviously not happen.

**Comment by nicolas-grekas** [comment] 2020-01-08 21:03
But it should be possible to have one single connection to a remote host and still do several h2 requests, since that's a main feature of the protocol. curl allows it.
Right now, multiplexing works by creating one socket per request, isn't it? Maybe I miss something :)

**Comment by trowski** [comment] 2020-01-08 22:03
H2 connections can have many streams per connection. Only a single connection is actually made.

The problem is that `LimitedConnectionPool` is too naïve and is allowing only a single request, even if the connection being used is H2.

@kelunik I think we should change `LimitedConnectionPool` to store the connections returned and attempt to reuse them for subsequent requests, only acquiring a lock and waiting if `Connection::getStream()` returns null.

**Comment by kelunik** [comment] 2020-01-08 22:26
The way it's currently written, it could have been a simple interceptor, I guess.

@trowski I don't see a way to implement that in the current implementation, because we don't ever have access to the connection object in `LimitedConnectionPool`. I'd have to be a separate implementation.

**Comment by trowski** [comment] 2020-01-08 22:28
Oh yes, right… it's only returning `Stream` objects. Yep, then it will have to be a whole new, separate implementation.

**Comment by nicolas-grekas** [comment] 2020-01-09 07:52
This is the callgraph of the above script *with the `LimitedConnectionPool` disabled*.

https://blackfire.io/profiles/20a80a98-340c-4327-b966-4c9db0c4f679/graph

As you can see, it opens several connections to the host.
stream_socket_enable_crypto is called 845 times, which makes it the most exclusive-time consuming function, and `ResourceSocket::__construct` is called 280 times.

I'll have a closer look, but if you have some hints meanwhile, I'd be happy to read them.

**Comment by nicolas-grekas** [comment] 2020-01-09 15:42
OK, here is what happens: the script requests more than the maximum number of allowed concurrent streams.

This means `$stream = yield $connection->getStream($request);` return `null` in `UnlimitedConnectionPool`, so that a second connection is opened on the limit is reached.
Then, all next requests open a separate connection, because `$isHttps && \count($connections) === 1` is `false` as of now.

Here is the blackfire profile that show only one connection is opened:
https://blackfire.io/profiles/4b7fe9f4-c427-45fb-9b4d-ce0d67881d4f/graph

I suppose the pool logic could be improved :)

**Comment by trowski** [comment] 2020-01-09 15:46
Thanks for figuring that out… I was scratching my head for the last half hour trying to figure out why the H2 connnection wasn't being reused. Can you try removing `&& \count($connections) === 1`. That *should* improve things quite a bit.

**Comment by nicolas-grekas** [comment] 2020-01-09 15:55
> Can you try removing `&& \count($connections) === 1`.

No difference, it still opens new connections after the threshold.
Please run the script if you want to verify :)

**Comment by trowski** [comment] 2020-01-09 16:08
Tried the script – it only used a single connection, but it also seemed to only be making one request at a time. Is there something I need to do so all requests are sent at once?

**Comment by trowski** [comment] 2020-01-09 16:35
@nicolas-grekas Just pushed 118194402d15e3001e1eca06d8ed78db0050b5b6, which should fix your problem. Please pull the latest master and give it a try. 😃

**Comment by kelunik** [comment] 2020-01-09 17:21
@trowski We can't leave https://github.com/amphp/http-client/commit/118194402d15e3001e1eca06d8ed78db0050b5b6 as is, because that will make the performance for HTTP/1.1 much worse, because every request needs to await any currently in progress connections. I will have to think about the optimal algorithm there.

**Comment by nicolas-grekas** [comment] 2020-01-09 18:12
> Just pushed 1181944, which should fix your problem

Confirmed! That's the right direction apparently :)

**Comment by trowski** [comment] 2020-01-09 18:25
@kelunik Yes, I realized that, but I wasn't sure about what a good solution there would be and I wanted to confirm that at least solved @nicolas-grekas's problem.

First idea I had is examine the first connection returned, and if HTTP/1.x, assume that the next one will also be HTTP/1.x and immediately make a new connection.

**Comment by kelunik** [comment] 2020-01-13 20:59
Closing, as this has been fixed on master.

**Closed by kelunik** 2020-01-13 20:59 UTC

**Comment by nicolas-grekas** [comment] 2020-01-14 14:46
Thank you!
Should I open a separate issue about LimitedConnectionPool?

**Comment by kelunik** [comment] 2020-01-14 16:59
Yup, please.
